#############################################################################
# Makefile for building: ../serwer_graficzny
# Generated by qmake (3.1) (Qt 6.2.4)
# Project:  out/pro/serwer_graficzny.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile.app out/pro/serwer_graficzny.pro
#############################################################################

MAKEFILE      = Makefile.app

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++17 -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -Iout/pro -I. -Iinc -I../libQGLViewer -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtXml -I/usr/include/x86_64-linux-gnu/qt6/QtCore -Iout/moc -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = serwer_graficzny1.0.0
DISTDIR = /home/michal/Documents/studia/sem_7/zaaw_met_prog/etap_2/serwer-z-tlem-Qt6/serwer_zrodla/out/obj/serwer_graficzny1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -L/home/michal/Documents/studia/sem_7/zaaw_met_prog/etap_2/serwer-z-tlem-Qt6/serwer_zrodla/../libQGLViewer/QGLViewer -lQGLViewer-qt6 -lSOIL /usr/lib/x86_64-linux-gnu/libQt6OpenGLWidgets.so /usr/lib/x86_64-linux-gnu/libQt6OpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Xml.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = out/obj/

####### Files

SOURCES       = src/gsv-BufferedScene.cpp \
		src/gsv-CommandBuffer.cpp \
		src/gsv-CommandInterpreter.cpp \
		src/gsv-Cuboid.cpp \
		src/gsv-GeomParams.cpp \
		src/gsv-GraphObject.cpp \
		src/gsv-GraphicsWindow.cpp \
		src/gsv-Map4DescGeomObjs.cpp \
		src/gsv-Map4SceneGeomObjs.cpp \
		src/gsv-Scene.cpp \
		src/gsv-SceneServer.cpp \
		src/gsv-ServerCommand.cpp \
		src/gsv-Tests.cpp \
		src/gsv-WgViewer3D.cpp \
		src/gtsDebug.cpp \
		src/main.cpp out/moc/moc_gsv-GraphicsWindow.cpp \
		out/moc/moc_gsv-WgViewer3D.cpp
OBJECTS       = out/obj/gsv-BufferedScene.o \
		out/obj/gsv-CommandBuffer.o \
		out/obj/gsv-CommandInterpreter.o \
		out/obj/gsv-Cuboid.o \
		out/obj/gsv-GeomParams.o \
		out/obj/gsv-GraphObject.o \
		out/obj/gsv-GraphicsWindow.o \
		out/obj/gsv-Map4DescGeomObjs.o \
		out/obj/gsv-Map4SceneGeomObjs.o \
		out/obj/gsv-Scene.o \
		out/obj/gsv-SceneServer.o \
		out/obj/gsv-ServerCommand.o \
		out/obj/gsv-Tests.o \
		out/obj/gsv-WgViewer3D.o \
		out/obj/gtsDebug.o \
		out/obj/main.o \
		out/obj/moc_gsv-GraphicsWindow.o \
		out/obj/moc_gsv-WgViewer3D.o
DIST          = /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		out/pro/.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		out/pro/out/pro/serwer_graficzny.pro inc/geomVector.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-BufferedScene.hh \
		inc/gsv-CommandBuffer.hh \
		inc/gsv-CommandInterpreter.hh \
		inc/gsv-Cuboid.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-GraphicsWindow.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Scene.hh \
		inc/gsv-SceneServer.hh \
		inc/gsv-ServerCommand.hh \
		inc/gsv-Vector3d.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-WgViewer3D.hh \
		inc/gtsDebug.hh src/gsv-BufferedScene.cpp \
		src/gsv-CommandBuffer.cpp \
		src/gsv-CommandInterpreter.cpp \
		src/gsv-Cuboid.cpp \
		src/gsv-GeomParams.cpp \
		src/gsv-GraphObject.cpp \
		src/gsv-GraphicsWindow.cpp \
		src/gsv-Map4DescGeomObjs.cpp \
		src/gsv-Map4SceneGeomObjs.cpp \
		src/gsv-Scene.cpp \
		src/gsv-SceneServer.cpp \
		src/gsv-ServerCommand.cpp \
		src/gsv-Tests.cpp \
		src/gsv-WgViewer3D.cpp \
		src/gtsDebug.cpp \
		src/main.cpp
QMAKE_TARGET  = serwer_graficzny
DESTDIR       = ../
TARGET        = ../serwer_graficzny


first: all
####### Build rules

../serwer_graficzny:  $(OBJECTS)  
	@test -d ../ || mkdir -p ../
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile.app: out/pro/serwer_graficzny.pro /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		out/pro/serwer_graficzny.pro \
		../libQGLViewer/QGLViewer/libQGLViewer-qt6.prl \
		/usr/lib/x86_64-linux-gnu/libQt6OpenGLWidgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6OpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Xml.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile.app out/pro/serwer_graficzny.pro
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
out/pro/serwer_graficzny.pro:
../libQGLViewer/QGLViewer/libQGLViewer-qt6.prl:
/usr/lib/x86_64-linux-gnu/libQt6OpenGLWidgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6OpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt6Xml.prl:
/usr/lib/x86_64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile.app out/pro/serwer_graficzny.pro

qmake_all: FORCE


all: Makefile.app ../serwer_graficzny

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents inc/geomVector.hh inc/gsv-AnglesRPY.hh inc/gsv-BufferedScene.hh inc/gsv-CommandBuffer.hh inc/gsv-CommandInterpreter.hh inc/gsv-Cuboid.hh inc/gsv-GeomParams.hh inc/gsv-GraphObject.hh inc/gsv-GraphicsWindow.hh inc/gsv-Map4DescGeomObjs.hh inc/gsv-Map4SceneGeomObjs.hh inc/gsv-RGB.hh inc/gsv-Scene.hh inc/gsv-SceneServer.hh inc/gsv-ServerCommand.hh inc/gsv-Vector3d.hh inc/gsv-Vector3i.hh inc/gsv-WgViewer3D.hh inc/gtsDebug.hh $(DISTDIR)/
	$(COPY_FILE) --parents src/gsv-BufferedScene.cpp src/gsv-CommandBuffer.cpp src/gsv-CommandInterpreter.cpp src/gsv-Cuboid.cpp src/gsv-GeomParams.cpp src/gsv-GraphObject.cpp src/gsv-GraphicsWindow.cpp src/gsv-Map4DescGeomObjs.cpp src/gsv-Map4SceneGeomObjs.cpp src/gsv-Scene.cpp src/gsv-SceneServer.cpp src/gsv-ServerCommand.cpp src/gsv-Tests.cpp src/gsv-WgViewer3D.cpp src/gtsDebug.cpp src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile.app


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: out/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) out/moc/moc_predefs.h
out/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++17 -O2 -Wall -Wextra -dM -E -o out/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: out/moc/moc_gsv-GraphicsWindow.cpp out/moc/moc_gsv-WgViewer3D.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) out/moc/moc_gsv-GraphicsWindow.cpp out/moc/moc_gsv-WgViewer3D.cpp
out/moc/moc_gsv-GraphicsWindow.cpp: inc/gsv-GraphicsWindow.hh \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		out/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/michal/Documents/studia/sem_7/zaaw_met_prog/etap_2/serwer-z-tlem-Qt6/serwer_zrodla/out/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/michal/Documents/studia/sem_7/zaaw_met_prog/etap_2/serwer-z-tlem-Qt6/serwer_zrodla/out/pro -I/home/michal/Documents/studia/sem_7/zaaw_met_prog/etap_2/serwer-z-tlem-Qt6/serwer_zrodla/out/pro/inc -I/home/michal/Documents/studia/sem_7/zaaw_met_prog/etap_2/serwer-z-tlem-Qt6/libQGLViewer -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtXml -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include inc/gsv-GraphicsWindow.hh -o out/moc/moc_gsv-GraphicsWindow.cpp

out/moc/moc_gsv-WgViewer3D.cpp: inc/gsv-WgViewer3D.hh \
		../libQGLViewer/QGLViewer/qglviewer.h \
		../libQGLViewer/QGLViewer/camera.h \
		../libQGLViewer/QGLViewer/keyFrameInterpolator.h \
		../libQGLViewer/QGLViewer/quaternion.h \
		../libQGLViewer/QGLViewer/vec.h \
		../libQGLViewer/QGLViewer/config.h \
		../libQGLViewer/QGLViewer/frame.h \
		../libQGLViewer/QGLViewer/constraint.h \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		out/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/michal/Documents/studia/sem_7/zaaw_met_prog/etap_2/serwer-z-tlem-Qt6/serwer_zrodla/out/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/michal/Documents/studia/sem_7/zaaw_met_prog/etap_2/serwer-z-tlem-Qt6/serwer_zrodla/out/pro -I/home/michal/Documents/studia/sem_7/zaaw_met_prog/etap_2/serwer-z-tlem-Qt6/serwer_zrodla/out/pro/inc -I/home/michal/Documents/studia/sem_7/zaaw_met_prog/etap_2/serwer-z-tlem-Qt6/libQGLViewer -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtXml -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include inc/gsv-WgViewer3D.hh -o out/moc/moc_gsv-WgViewer3D.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

out/obj/gsv-BufferedScene.o: src/gsv-BufferedScene.cpp inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-BufferedScene.o src/gsv-BufferedScene.cpp

out/obj/gsv-CommandBuffer.o: src/gsv-CommandBuffer.cpp inc/gsv-CommandBuffer.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-CommandBuffer.o src/gsv-CommandBuffer.cpp

out/obj/gsv-CommandInterpreter.o: src/gsv-CommandInterpreter.cpp inc/gtsDebug.hh \
		inc/gsv-CommandInterpreter.hh \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-CommandBuffer.hh \
		inc/gsv-ServerCommand.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-CommandInterpreter.o src/gsv-CommandInterpreter.cpp

out/obj/gsv-Cuboid.o: src/gsv-Cuboid.cpp inc/gsv-Cuboid.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gtsDebug.hh \
		../libQGLViewer/QGLViewer/qglviewer.h \
		../libQGLViewer/QGLViewer/camera.h \
		../libQGLViewer/QGLViewer/keyFrameInterpolator.h \
		../libQGLViewer/QGLViewer/quaternion.h \
		../libQGLViewer/QGLViewer/vec.h \
		../libQGLViewer/QGLViewer/config.h \
		../libQGLViewer/QGLViewer/frame.h \
		../libQGLViewer/QGLViewer/constraint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-Cuboid.o src/gsv-Cuboid.cpp

out/obj/gsv-GeomParams.o: src/gsv-GeomParams.cpp inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-GeomParams.o src/gsv-GeomParams.cpp

out/obj/gsv-GraphObject.o: src/gsv-GraphObject.cpp inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-GraphObject.o src/gsv-GraphObject.cpp

out/obj/gsv-GraphicsWindow.o: src/gsv-GraphicsWindow.cpp inc/gsv-GraphicsWindow.hh \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-WgViewer3D.hh \
		../libQGLViewer/QGLViewer/qglviewer.h \
		../libQGLViewer/QGLViewer/camera.h \
		../libQGLViewer/QGLViewer/keyFrameInterpolator.h \
		../libQGLViewer/QGLViewer/quaternion.h \
		../libQGLViewer/QGLViewer/vec.h \
		../libQGLViewer/QGLViewer/config.h \
		../libQGLViewer/QGLViewer/frame.h \
		../libQGLViewer/QGLViewer/constraint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-GraphicsWindow.o src/gsv-GraphicsWindow.cpp

out/obj/gsv-Map4DescGeomObjs.o: src/gsv-Map4DescGeomObjs.cpp inc/gsv-Map4DescGeomObjs.hh \
		inc/gtsDebug.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-Map4DescGeomObjs.o src/gsv-Map4DescGeomObjs.cpp

out/obj/gsv-Map4SceneGeomObjs.o: src/gsv-Map4SceneGeomObjs.cpp inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gtsDebug.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-Map4SceneGeomObjs.o src/gsv-Map4SceneGeomObjs.cpp

out/obj/gsv-Scene.o: src/gsv-Scene.cpp inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-Cuboid.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-Scene.o src/gsv-Scene.cpp

out/obj/gsv-SceneServer.o: src/gsv-SceneServer.cpp inc/gsv-SceneServer.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-CommandInterpreter.hh \
		inc/gsv-BufferedScene.hh \
		inc/gsv-CommandBuffer.hh \
		inc/gsv-ServerCommand.hh \
		inc/gtsDebug.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-SceneServer.o src/gsv-SceneServer.cpp

out/obj/gsv-ServerCommand.o: src/gsv-ServerCommand.cpp inc/gsv-ServerCommand.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-Cuboid.hh \
		inc/gtsDebug.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-ServerCommand.o src/gsv-ServerCommand.cpp

out/obj/gsv-Tests.o: src/gsv-Tests.cpp inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-ServerCommand.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-Map4SceneGeomObjs.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-Tests.o src/gsv-Tests.cpp

out/obj/gsv-WgViewer3D.o: src/gsv-WgViewer3D.cpp inc/gsv-WgViewer3D.hh \
		../libQGLViewer/QGLViewer/qglviewer.h \
		../libQGLViewer/QGLViewer/camera.h \
		../libQGLViewer/QGLViewer/keyFrameInterpolator.h \
		../libQGLViewer/QGLViewer/quaternion.h \
		../libQGLViewer/QGLViewer/vec.h \
		../libQGLViewer/QGLViewer/config.h \
		../libQGLViewer/QGLViewer/frame.h \
		../libQGLViewer/QGLViewer/constraint.h \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-BackgroundImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gsv-WgViewer3D.o src/gsv-WgViewer3D.cpp

out/obj/gtsDebug.o: src/gtsDebug.cpp inc/gtsDebug.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/gtsDebug.o src/gtsDebug.cpp

out/obj/main.o: src/main.cpp inc/gsv-CommandInterpreter.hh \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-CommandBuffer.hh \
		inc/gsv-ServerCommand.hh \
		inc/gsv-WgViewer3D.hh \
		../libQGLViewer/QGLViewer/qglviewer.h \
		../libQGLViewer/QGLViewer/camera.h \
		../libQGLViewer/QGLViewer/keyFrameInterpolator.h \
		../libQGLViewer/QGLViewer/quaternion.h \
		../libQGLViewer/QGLViewer/vec.h \
		../libQGLViewer/QGLViewer/config.h \
		../libQGLViewer/QGLViewer/frame.h \
		../libQGLViewer/QGLViewer/constraint.h \
		inc/gsv-SceneServer.hh \
		inc/gtsDebug.hh \
		inc/gsv-Const.h \
		inc/gsv-GraphicsWindow.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/main.o src/main.cpp

out/obj/moc_gsv-GraphicsWindow.o: out/moc/moc_gsv-GraphicsWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/moc_gsv-GraphicsWindow.o out/moc/moc_gsv-GraphicsWindow.cpp

out/obj/moc_gsv-WgViewer3D.o: out/moc/moc_gsv-WgViewer3D.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/obj/moc_gsv-WgViewer3D.o out/moc/moc_gsv-WgViewer3D.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

